import type { Metadata } from "next";
import "./globals.css";
import Nav from  "./components/์Nav"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{fontSize:"65.5%"}}>
      <body>
          <Nav/>
          <div className="div-layout overflow-x-hidden">
            {children}
          </div>


      </body>
    </html>
  );
}
